kind: Namespace
apiVersion: v1
metadata:
  name: dancing-gopher
  labels:
    name: dancing-gopher
---
apiVersion: v1
data:
  tls.crt:
  tls.key:
kind: Secret
metadata:
  labels:
    name: dancing-gopher
  name: dancing-gopher-certs
  namespace: dancing-gopher
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dancing-gopher
  labels:
    name: dancing-gopher
  namespace: dancing-gopher
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dancing-gopher
  template:
    metadata:
      labels:
        name: dancing-gopher
    spec:
      containers:
        - name: dancing-gopher
          image: quay.io/zerodayz/dancing-gopher:latest
          ports:
            - name: dancing-gopher
              containerPort: 8080
          volumeMounts:
            - mountPath: /certs
              name: dancing-gopher-certificates
              readOnly: true
      volumes:
        - name: dancing-gopher-certificates
          secret:
            defaultMode: 420
            optional: false
            secretName: dancing-gopher-certs
---
apiVersion: v1
kind: Service
metadata:
  name: dancing-gopher-svc
  namespace: dancing-gopher
spec:
  selector:
    name: dancing-gopher
  ports:
    - name: gopher-http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: gopher-https
      port: 443
      protocol: TCP
      targetPort: 8443
---
apiVersion: v1
kind: Route
metadata:
  name: dancing-gopher-https
  namespace: dancing-gopher
spec:
  port:
    targetPort: gopher-https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: dancing-gopher-svc
---
apiVersion: v1
kind: Route
metadata:
  name: dancing-gopher-http
  namespace: dancing-gopher
spec:
  port:
    targetPort: gopher-http
  to:
    kind: Service
    name: dancing-gopher-svc
  path: "/"